### PR TITLE
Upgrade to Material You and dyanmic colors

### PR DESCRIPTION
**Pull request by ebraminio**
Upgrade to Material You and dynamic colors, probably can't be applied just right now as material library is beta01 and isn't stable, the following screencast is taken from Android Sv2 image of the emulator,

https://user-images.githubusercontent.com/833473/141698932-b5e7662a-cd45-4cf4-8c5a-74e0fc039f3b.mov

### CODE REVIEW

**Comment by bubelov** [comment]
@ebraminio it mostly works fine on my phone, two minor issues:

1. Top app bar changes color while scrolling, it looks like it's jumping between two colors
2. Bottom bar colors are slightly different in light mode. I'm using Android 11

Here is the screenshot showing those issues:

index

**Comment by bubelov** [comment]
@ebraminio I played with it a bit more and decided to limit it to Android 12 and later. There aren't a lot of people who uses Android 12 so we can experiment and hear some feedback. People who use older Android will have the old theme for now. I'll file an issue for tracking migration to Material 3

**Comment by ebraminio** [comment]
> I played with it a bit more and decided to limit it to Android 12 and later. There aren't a lot of people who uses Android 12 so we can experiment and hear some feedback. People who use older Android will have the old theme for now. I'll file an issue for tracking migration to Material 3

Sorry for not spotting the issues, limiting to Android 12 feels like a good short term plan, thanks :)

**Comment by ebraminio** [comment]
have put some time on this and still clueless how the scroll is making effect there and how that only happens in Material 3 :/

**Comment by bubelov** [comment]
@ebraminio might be an issue with beta, or maybe it supposed to change color slightly to indicate that the content is up-scrollable, but it's just a speculation. I'll try to update the deps related to list widget, etc. If this won't help, it probably makes sense to wait for Material 3 to go out of beta before rolling it up to older versions of Android. By the way, I moved all v31 related styles to a single file, so it's easier to play with the new theme without affecting the lower targets:

https://github.com/bubelov/news/blob/master/app/src/main/res/values-v31/styles.xml

**Pull request merged**
